### ISSUE TITLE
pulp::simd_type! generates a missing import error

### ISSUE THREAD

**Issue by IceTDrinker** [sarah-ek/pulp#10]
I'm guessing the macro uses MaybeUninit directly instead of a fully qualified path like std::mem::MaybeUninit or core::mem::MaybeUninit

Fix is straightforward on our end but could be nice for people who use this macro in the wild :)

```console
error[E0412]: cannot find type `MaybeUninit` in this scope
   --> tfhe-ntt/src/lib.rs:135:1
    |
135 | / pulp::simd_type! {
136 | |     struct V4IFma {
137 | |         pub sse: "sse",
138 | |         pub sse2: "sse2",
...   |
157 | |     }
158 | | }
    | |_^ not found in this scope
    |
    = note: this error originates in the macro `pulp::simd_type` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this union
    |
78  + use std::mem::MaybeUninit;
    |
```

**Comment by sarah-quinones** [comment]
thanks. gonna fix it soon, nice to see you again btw 😄

**Comment by IceTDrinker** [comment]
> thanks. gonna fix it soon, nice to see you again btw 😄

Likewise 😄 👋

**Comment by sarah-quinones** [comment]
btw, if you send me a DM on discord, i have some multithreading optimizations you might be interested in chatting about

**Comment by IceTDrinker** [comment]
> btw, if you send me a DM on discord, i have some multithreading optimizations you might be interested in chatting about

definitely ! Same handle :)

**Comment by IceTDrinker** [comment]
I meant, I don't think I have your handle but mine's the same

**Comment by sarah-quinones** [comment]
fixed
