### ISSUE TITLE
Build error on nightly-2024-02-05

### ISSUE THREAD

**Issue by swfsql** [sarah-ek/pulp#5]
Hello, I'm sorry for just referring to another issue - https://github.com/Lokathor/bytemuck/issues/224 - but similarly to it it also applies for `pulp`. The `stdsimd` feature name has been split into other features, and this is preventing this library from being built on nightly.

As for this case, I'm not familiar with that feature nor with this library, so I'm refrain from trying to create a PR, but it may be enough to make similar changes (placing `stdarch_x86_avx512` in place of `stdsimd`) - but I'm not sure if more changes would be needed for other features and/or architectures.

- https://github.com/sarah-ek/pulp/blob/7e96a0ba34e5700ffe3939075c19c2b0c1257206/pulp/src/lib.rs#L65

The same applies for gemm:
- https://github.com/search?q=repo%3Asarah-ek%2Fgemm+stdsimd&type=code

Thanks!

**Comment by sarah-quinones** [comment]
thanks! i'll try to fix this soon.

**Comment by sarah-quinones** [comment]
fixed in 0.18.7
